name: CI 
on: 
  push:
branches:
  - main
jobs:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: install
        run: npm install 
        name: run 
        run: npm test